version: '3.8'

services:
  api:
    build: .
    ports:
      - "5130:5130"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5130
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - JwtKey=${JWT_KEY}